language: ruby

rvm:
  - 2.5.3

services:
  - postgresql

before_script:
  - psql -c 'create database job_hunt_organiser_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:create

script:
  - bundle exec rails db:migrate RAILS_ENV=test
